apiVersion: v1
data:
  mapRoles: "- groups:\n  - system:masters\n  rolearn: arn:aws:iam::127201933701:role/UdacityFlaskDeployCBKubectlRole\n
    \ username: build      \n- groups:\n  - system:bootstrappers\n  - system:nodes\n
    \ rolearn: arn:aws:iam::127201933701:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-BD72MA5VB1ML\n
    \ username: system:node:{{EC2PrivateDNSName}}\n"
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-24T13:21:23Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "4823"
  uid: e7ff5126-3688-426e-a959-847b79202d82
